INSERT INTO tb_hq_list (name) VALUES ('Sagas Sombrias e Realistas');
INSERT INTO tb_hq_list (name) VALUES ('Épicos Cósmicos e Fantásticos');


INSERT INTO tb_dc (title, hq_year, genre, authors, score, img_url, short_description, long_description) VALUES ('Batman: A Piada Mortal', 1988, 'Graphic Novel, Psicológico', 'Alan Moore, Brian Bolland', 4.8, 'https://m.media-amazon.com/images/I/81-Lp-p5g6L._AC_UF1000,1000_QL80_.jpg', 'Uma sombria história de origem do Coringa que explora a loucura e testa os limites morais do Batman.', 'Considerada uma das histórias mais influentes e sombrias do Batman, A Piada Mortal mergulha na psique do Coringa, apresentando uma possível origem trágica para o vilão. A trama mostra o Palhaço do Crime tentando provar que um dia ruim é o suficiente para enlouquecer qualquer um, e seu alvo é o Comissário Gordon.');
INSERT INTO tb_dc (title, hq_year, genre, authors, score, img_url, short_description, long_description) VALUES ('Watchmen', 1986, 'Mistério, Super-herói, Ficção Política', 'Alan Moore, Dave Gibbons', 5.0, 'https://m.media-amazon.com/images/I/8170ppc+z6L._AC_UF1000,1000_QL80_.jpg', 'Em uma realidade alternativa, um grupo de heróis aposentados investiga o assassinato de um dos seus e descobre uma conspiração mortal.', 'Watchmen desconstruiu o gênero de super-heróis. Ambientado em uma história alternativa onde heróis mascarados alteraram o curso de eventos históricos, a trama segue uma investigação que desvenda uma conspiração que pode mudar o mundo. É uma obra complexa que explora poder, moralidade e a condição humana.');
INSERT INTO tb_dc (title, hq_year, genre, authors, score, img_url, short_description, long_description) VALUES ('Batman: O Cavaleiro das Trevas', 1986, 'Distopia, Super-herói, Ação', 'Frank Miller', 4.9, 'https://m.media-amazon.com/images/I/811jev9l-GL._AC_UF1000,1000_QL80_.jpg', 'Um Bruce Wayne envelhecido retorna da aposentadoria para combater o crime em uma Gotham City futurista e decadente.', 'Esta minissérie redefiniu o Batman para uma geração. Frank Miller apresenta um futuro sombrio onde um Batman de 55 anos, amargurado e mais violento, volta a vestir o manto para enfrentar uma nova onda de criminosos e um governo hostil, culminando em um confronto épico com o Superman.');
INSERT INTO tb_dc (title, hq_year, genre, authors, score, img_url, short_description, long_description) VALUES ('O Batman que Ri', 2018, 'Terror, Super-herói, Ação', 'Scott Snyder, Jock', 4.4, 'https://m.media-amazon.com/images/I/81P2iNPIoEL._AC_UF1000,1000_QL80_.jpg', 'Uma versão aterrorizante do Batman vinda do Multiverso Sombrio, que possui a inteligência do Batman e a insanidade do Coringa.', 'Surgido no evento "Noites de Trevas: Metal", o Batman que Ri é Bruce Wayne de uma Terra alternativa onde foi exposto à toxina do Coringa. Nesta minissérie, ele chega ao universo principal da DC para espalhar o caos, forçando o Batman a confrontar a sua pior versão e a tomar medidas extremas para detê-lo.');
INSERT INTO tb_dc (title, hq_year, genre, authors, score, img_url, short_description, long_description) VALUES ('Batman: A Corte das Corujas', 2011, 'Mistério, Ação, Super-herói', 'Scott Snyder, Greg Capullo', 4.8, 'https://m.media-amazon.com/images/I/A1+j-2FvjJL._AC_UF1000,1000_QL80_.jpg', 'Batman descobre uma sociedade secreta e antiga, a Corte das Corujas, que tem controlado Gotham City das sombras por séculos.', 'No início da fase dos Novos 52, a Corte das Corujas, uma cabala secreta de aristocratas, governa Gotham há gerações usando assassinos mortais conhecidos como Garras. Batman é levado ao limite físico e mental para expor e combater essa conspiração que ameaça destruir tudo o que ele representa. Esta saga é aclamada como um clássico moderno do personagem.');

INSERT INTO tb_dc (title, hq_year, genre, authors, score, img_url, short_description, long_description) VALUES ('Reino do Amanhã', 1996, 'Super-herói, Ficção Científica', 'Mark Waid, Alex Ross', 4.7, 'https://m.media-amazon.com/images/I/911b4o1i17L._AC_UF1000,1000_QL80_.jpg', 'Num futuro onde a nova geração de heróis é irresponsável e perigosa, Superman retorna para guiar o mundo, gerando um conflito de ideologias.', 'Num futuro onde a nova geração de metahumanos é irresponsável, Superman e a Liga da Justiça retornam da aposentadoria para guiar o mundo, o que leva a um conflito de ideologias e uma batalha que pode destruir o planeta. A arte fotorrealista de Alex Ross é um marco na indústria de quadrinhos.');
INSERT INTO tb_dc (title, hq_year, genre, authors, score, img_url, short_description, long_description) VALUES ('Crise nas Infinitas Terras', 1985, 'Crossover, Aventura Cósmica', 'Marv Wolfman, George Pérez', 4.6, 'https://m.media-amazon.com/images/I/A16LpcOFbSL._AC_UF1000,1000_QL80_.jpg', 'Heróis e vilões de múltiplos universos se unem para impedir que uma entidade cósmica destrua toda a realidade.', 'O megaevento que redefiniu o Universo DC. O Antimonitor, uma entidade cósmica, começa a destruir as diversas Terras do multiverso, forçando heróis e vilões de todas as realidades a se unirem para salvar o que resta da existência. A saga é famosa por suas consequências drásticas, incluindo a morte de personagens icônicos.');
INSERT INTO tb_dc (title, hq_year, genre, authors, score, img_url, short_description, long_description) VALUES ('Grandes Astros: Superman', 2005, 'Super-herói, Ficção Científica, Drama', 'Grant Morrison, Frank Quitely', 5.0, 'https://m.media-amazon.com/images/I/81xBe5e-wIL._AC_UF1000,1000_QL80_.jpg', 'Superexposto ao sol, Superman ganha poderes incríveis mas descobre que está morrendo, decidindo realizar feitos heroicos como seus últimos trabalhos.', 'Considerada por muitos a história definitiva do Superman, esta obra mostra o Homem de Aço em seus últimos dias. Sabendo que seu tempo é limitado, ele embarca em uma série de doze trabalhos fantásticos, que servem como uma carta de amor à mitologia e à esperança que o personagem representa.');
INSERT INTO tb_dc (title, hq_year, genre, authors, score, img_url, short_description, long_description) VALUES ('Sandman: Prelúdios e Noturnos', 1989, 'Fantasia Sombria, Horror, Mitologia', 'Neil Gaiman, Sam Kieth', 5.0, 'https://m.media-amazon.com/images/I/910EHAYyTzL._AC_UF1000,1000_QL80_.jpg', 'Após 70 anos de aprisionamento, Morpheus, o Senhor dos Sonhos, escapa e inicia uma jornada para recuperar seus artefatos de poder.', 'Este é o arco de abertura da obra-prima de Neil Gaiman. Sonho, um dos Perpétuos, é capturado por um culto e mantido prisioneiro. Ao se libertar, ele encontra seu reino em ruínas e precisa reaver seus objetos de poder, em uma jornada que o leva a encontros com personagens da DC, demônios e a própria Morte.');
INSERT INTO tb_dc (title, hq_year, genre, authors, score, img_url, short_description, long_description) VALUES ('Ponto de Ignição (Flashpoint)', 2011, 'Super-herói, Realidade Alternativa', 'Geoff Johns, Andy Kubert', 4.5, 'https://m.media-amazon.com/images/I/91TcaO2-wzL._AC_UF1000,1000_QL80_.jpg', 'Barry Allen acorda em uma realidade distorcida onde ele não tem poderes, sua mãe está viva, e o mundo está à beira da destruição.', 'Flashpoint é o evento cataclísmico que deu origem à reformulação dos Novos 52. Barry Allen volta no tempo para salvar sua mãe, mas o ato fratura a linha do tempo, criando um presente sombrio onde Amazonas e Atlantes estão em guerra e Thomas Wayne é um Batman violento. Barry precisa consertar a realidade antes que ela se aniquile.');

INSERT INTO tb_belonging (list_id, hq_id, position) VALUES (1, 1, 0);
INSERT INTO tb_belonging (list_id, hq_id, position) VALUES (1, 2, 1);
INSERT INTO tb_belonging (list_id, hq_id, position) VALUES (1, 3, 2);
INSERT INTO tb_belonging (list_id, hq_id, position) VALUES (1, 4, 3);
INSERT INTO tb_belonging (list_id, hq_id, position) VALUES (1, 5, 4);

INSERT INTO tb_belonging (list_id, hq_id, position) VALUES (2, 6, 0);
INSERT INTO tb_belonging (list_id, hq_id, position) VALUES (2, 7, 1);
INSERT INTO tb_belonging (list_id, hq_id, position) VALUES (2, 8, 2);
INSERT INTO tb_belonging (list_id, hq_id, position) VALUES (2, 9, 3);
INSERT INTO tb_belonging (list_id, hq_id, position) VALUES (2, 10, 4);